version: 1
disable_existing_loggers: false
formatters:
  json:
    format: "%(message)s"
    class: "app.logging.config.JSONFormatter"
  console:
    format: "%(asctime)s [%(levelname)-7s] %(name)s: %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: json
    filename: logs/app.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
  console:
    class: logging.StreamHandler
    level: DEBUG  # Overridden by environment in config.py
    formatter: console  # Overridden by LOG_CONSOLE_JSON
loggers:
  devanchor:
    level: DEBUG  # Overridden by environment in config.py
    handlers: [file, console]
    propagate: false
root:
  level: INFO
  handlers: [console]